#!/bin/bash

# test for comparison of UVM and non-UVM performance of kernel running on device

echo "Running test (single thread)..."
make clean
rm -f tmp_*
make OMP=0
for i in {0..9}
  do
     make test_uvm_h >> tmp_uvm
     make test_default_h >> tmp_default 
 done

#measure UVM compute time
echo "UVM"
grep "compute time" < tmp_uvm | awk -F ' ' '{print $4}'

#measure non-uvm compute time
echo "no UVM"
grep "compute time" < tmp_default | awk -F ' ' '{print $4}'

echo "Running test (multi thread)..."
make clean
rm -f tmp_*
make OMP=1
for i in {0..9}
  do
     make test_uvm_h >> tmp_uvm
     make test_default_h >> tmp_default 
 done

#measure UVM compute time
echo "UVM"
grep "compute time" < tmp_uvm | awk -F ' ' '{print $4}'

#measure non-uvm compute time
echo "no UVM"
grep "compute time" < tmp_default | awk -F ' ' '{print $4}'

rm -f tmp_*
